### ISSUE TITLE
Create ElasticSearch for dev

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2936]
We need an ElasticSearch server for dev

 - SCL3 version 2.4.5
 - Plugins
   - Polish analyzer https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-stempel.html

All the data can get rebuilt from the database.

**Comment by metadave** [comment]
We've had success with [elastic.co](https://www.elastic.co/cloud) hosting for MDN.

MDN specs:
- AWS / us-west-2
- 4GB memory
- 96 GB SSD
- HA enabled
= $228/month


See also:
https://github.com/mozmeao/infra/issues/193
https://github.com/mozmeao/infra/issues/383

**Comment by metadave** [comment]
I can create this at any time, but I'd like to get the SUMO/AWS estimate set first.

**Comment by metadave** [comment]
let's use the [Elasticsearch helm chart](https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch) for the dev instance.

**Comment by metadave** [comment]
I've spent about a day trying to get [this](https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch) chart to run in Frankfurt with v2.4.5, but the pods won't start due to problems with persistent volume timeouts. 

For development, I'd suggest a single [elastic.co](https://www.elastic.co/cloud/as-a-service/pricing) 1GB memory/24GB disk space AWS instance in a single region for $38-55/month (depending on region selected). The earliest supported version in elastic.co is 2.4.6, and the [Polish analyzer](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-stempel.html) can be added by clicking a checkbox.

**Comment by glogiotatidis** [comment]
> For development, I'd suggest a single elastic.co 1GB memory/24GB disk space AWS instance in a single region for $38-55/month (depending on region selected). The earliest supported version in elastic.co is 2.4.6, and the Polish analyzer can be added by clicking a checkbox.

elastic.co with 2.4.6 and click-to-get polish analyzer wfm just fine.

**Comment by metadave** [comment]
@glogiotatidis dev instance provisioned in elastic.co, let me know when you have the private repo configured and I'll add the creds there.
