### ISSUE TITLE
provision RDS instance

### ISSUE THREAD

**Issue by metadave** [mozilla/kitsune#2942]
Using Terraform, create a multi-AZ RDS instance in AWS. 

We'll need to specify a 30 minute window for backups, and a 30 minute window for general maintenance. @glogiotatidis Do you have an idea of when would be a good time for these windows? 

See [this](https://github.com/mozilla/kitsune/issues/2937) issue for version info.

**Comment by metadave** [comment]
"rough draft": https://github.com/mozmeao/infra/pull/638

**Comment by glogiotatidis** [comment]
> We'll need to specify a 30 minute window for backups, and a 30 minute window for general maintenance. @glogiotatidis Do you have an idea of when would be a good time for these windows?

Well we get traffic from allover the world. According to GA the 3 top countries are US, Germany and Japan, a full range of timezones :D 

I'd place those maintenance windows around UTC+12 and UTC+11.5

Since those are multi-az we shouldn't be expecting any downtime given thaf everything goes well, correct?

**Comment by metadave** [comment]
> Since those are multi-az we shouldn't be expecting any downtime given thaf everything goes well, correct?
[In theory](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html), yes.

**Comment by metadave** [comment]
RDS automation in https://github.com/mozmeao/infra/pull/638, but not provisioned in AWS for dev.
