### ISSUE TITLE
Switch Sessions to cached_db

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3010]
After deploy to AWS, we want to switch cached_db sessions to maintain sessions among datacenters.

 - Verify that we don't create a session unless needed (i.e. only when users are writing logged in or otherwise)
 - Re-enable test #2963 
 - Switch to cached_db sessions

**Comment by pmac** [comment]
Is it possible to region-pin an authenticated user instead so that we can just use cache for sessions? Perhaps that is even more complicated. I'm mainly wondering if there is some AWS magic that can help us with this one? I'm not opposed to using the DB for this, but minimizing DB writes would be good.

**Comment by glogiotatidis** [comment]
Adding a few more thoughts

- Since we're going to have the website behind a latency based traffic policy (right?) the users will be in a way region-pinned. 
- We are not generating a session object for anonymous users thus the db writes are limited to only authenticated users.
- It appears we have <500 logins per day for which we'll hit the db with new session data. All others should hit only the cache given that it's big enough.
- `cached_db` used to be the default before spamming ourselves with a Fx addon. Since then we changed code to not create sessions for anonymous users ([bug 1363892#c17](https://bugzilla.mozilla.org/show_bug.cgi?id=1363892#c17)) but we never reverted to `cached_db` due to the upcoming aws move.

**Comment by pmac** [comment]
Now that we're going to have the 2 main deployments in a single AWS region, perhaps we don't need to do this after all? I'm still not opposed to it, but storing them in the cache (Redis) only seems fine also, especially since the hot-spare deployment will be read-only for some time during a failover.

**Comment by glogiotatidis** [comment]
> Now that we're going to have the 2 main deployments in a single AWS region, perhaps we don't need to do this after all? I'm still not opposed to it, but storing them in the cache (Redis) only seems fine also, especially since the hot-spare deployment will be read-only for some time during a failover.

Yes, let's keep it the way it is. It's a env variable change after all. Will record in the decision log and close this issue. Thanks.
