### ISSUE TITLE
Setup search indexing for hot-spare region

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3030]
For our read-only spare region we won't be able to use the ORM model save signals to trigger indexing of new and modified questions and articles. We can reindex all of the articles nightly, but the questions are too numerous to do in that way. For now we'll just do an initial full indexing run, then set up a nightly job to freshen the index by reindexing all of the articles and all of the questions that have a modified date within the past two days. This should cover things if the nightly job fails one time.

I'll be writing up another issue to cover how we'd like to set up search indexing in future to more reliably avoid these issues.

**Comment by glogiotatidis** [comment]
This approach will be also useful while we're replicating from SCL3 to AWS to keep the Oregon based indices fresh for the READ_ONLY test and for when we actually flip the switch.

We want some like [`reindex_kb`](https://github.com/mozilla/kitsune/blob/master/kitsune/wiki/cron.py#L51) command but for questions. The command must support date filtering so we can reindex only the questions which have changed the last 24/48 hours.

@pmac is this something you have capacity and interest to take on?

**Comment by pmac** [comment]
I also like your idea from #3013 that the "master" data center can just ping all of the ES instances. Do you think it'd be best to just go ahead with that plan and not do this, or should we do this for now and move to the multi-region-ping thing later?

In either case yes, I'm ready to take this on.

**Comment by glogiotatidis** [comment]
I think both approaches will work. I'm leaning towards your idea since we already have `reindex_kb` and the setup seems simpler than extending the to-be-replaced elasticutils.

**Comment by pmac** [comment]
We discussed in a meeting and this is the way we'll go. Thanks all! I'll get on this very soon.

**Comment by pmac** [comment]
I've had more of a look around in the code and I'm not seeing any modified date fields for articles, so this "index those modified in the last hour" approach might require a bit more work. Here's what I'm thinking now:

Instead of altering the Article model (and others) I'm thinking a single new model designed to capture the type, ID, and timestamp of a modification. This will allow us to easily query for those for the past X amount of time, and add them to the queue for indexing. We'd also have a cron job to clean up entries in this table older than several times the normal indexing interval (likely 24 to 48 hours). Entries in this table could be added via the existing signals. We could leave the main region using the signals as they are and only use this new table in the spare region, or we could switch all instances to index on an interval using this new table. I'm on the fence on that at the moment myself. To recap: the proposed flow is:

1. Indexable model instance is modified
2. Signal is fired that adds a row to a DB table that records the model name, PK of the modified instance, and a timestamp
3. A job runs on a schedule (e.g. every 5 min) and adds all documents modified < some time (e.g. 1 hour) ago to the queue for an [indexing job](https://github.com/mozilla/kitsune/blob/master/kitsune/wiki/cron.py#L51) to process.
4. A separate job runs every day to clean up this DB table so that it doesn't grow unlimited.

Let me know what you think.

**Comment by glogiotatidis** [comment]
> I've had more of a look around in the code and I'm not seeing any modified date fields for articles, so this "index those modified in the last hour" approach might require a bit more work.

Since Documents are wiki style and each save creates a new revision, maybe we can rely on revision.created timestamp?

```python 
dt = datetime.utcnow() - timedelta(hours=1)
Document.objects.filter(revisions__created__gte=dt)
```

**Comment by glogiotatidis** [comment]
We have the following mapping types:

 - kitsune.customercare.models.ReplyMetricsMappingType
 - kitsune.forums.models.ThreadMappingType
 - kitsune.questions.models.AnswerMetricsMappingType
 - kitsune.questions.models.QuestionMappingType
 - kitsune.users.models.UserMappingType
 - kitsune.wiki.models.DocumentMappingType
 - kitsune.wiki.models.RevisionMetricsMappingType

The first one (kitsune.customercare.models.ReplyMetricsMappingType) we ignore since customercare (i.e. Army of Awesome - AoA) is deprecated and code will be deleted.

For the rest:
 - the `esreindex` management command, re-indexes all thoses types.
 - it takes different arguments, to limit the re-indexes to a percentage or a "critical mass"
 - It feels like we can extend this, to include after datetime argument


 - kitsune.forums.models.ThreadMappingType
   - base filter on Thread.last_post.created
 - kitsune.questions.models.AnswerMetricsMappingType
   - base filter on Answer.updated
 - kitsune.questions.models.QuestionMappingType
   - base filter on Question.updated 
 - kitsune.wiki.models.DocumentMappingType
   - base filter on Document.current_revision.created
 - kitsune.wiki.models.RevisionMetricsMappingType
   - base filter on Revision.created
 - kitsune.users.models.UserMappingType
   - OK this is an odd one since there's no timestamp we can use. On the bright side, this mapping type is used in the non-critical index probably for some dashboards. It's not used in search or advanced search. We don't have to replicate to the READ_ONLY region since nobody will be able to see the dashboards anyways.

What do you think @pmac?

**Comment by pmac** [comment]
Great! Thanks for all that info. I missed the revisions clearly :( I was looking at `Revision` in `wiki/modes.py` which doesn't have a date, but failed to look at the base class `AbstractRevision`. New model to track changes proposal withdrawn :)

**Comment by glogiotatidis** [comment]
> Great! Thanks for all that info. I missed the revisions clearly :( I was looking at Revision in wiki/modes.py which doesn't have a date, but failed to look at the base class AbstractRevision. New model to track changes proposal withdrawn :)

woohoo, full steam ahead! 🚂
