### ISSUE TITLE
Remove django-badger

### ISSUE THREAD

**Issue by rtanglao** [mozilla/kitsune#3045]
**edit from @pmac**

We need to move away from django-badger as it's been abandoned for quite a while and is no longer serving our needs, and is blocking Django upgrades (see #3177). I believe the options are:

1. Steal the useful bits of django-badger and add them as an app in kitsune itself (kitsune/badger e.g.).
2. Find a new and well-maintained Django badge library and port our data and rules to it.

My guess is that 1) will be the easier way to go, but 2) could well work out depending on django-badger's current state.

----

##  django-badger does not support S3 media backend

[as per bug 1402945](https://bugzilla.mozilla.org/show_bug.cgi?id=1429897#c1)

# Steps to Reproduce

1. I tried to upload a 256x256 PNG badges for [2017 kb](https://bugzilla.mozilla.org/attachment.cgi?id=8948312), [2017 l10n](https://bugzilla.mozilla.org/attachment.cgi?id=8948313), [2017 aoa](https://bug1429897.bmoattachments.org/attachment.cgi?id=8948310), [2017](https://bugzilla.mozilla.org/attachment.cgi?id=8948311) forum here:
https://support.mozilla.org/admin/badger/badge/

2. And I didn't receive an error message so I thought the badge graphic upload upload was successful

# Expected Results

The badge(s) are displayed in a user profile e.g.
https://support.mozilla.org/en-US/user/rtanglao

# Actual Results

The profile doesn't display the PNG just text.

e.g. my profile at https://support.mozilla.org/en-US/user/rtanglao  just shows 
"2017 Support Forum Badge"
AND
"2017 KB Badge

**Comment by metadave** [comment]
The 2 broken images are behind the Cloudfront CDN, which points at an S3 bucket. I don't see the files/directories in S3. 

- https://prod-cdn.sumo.mozilla.net/uploads/badge/b/5/b5bbb96c16466e29bfbda6b4b5f89506_image_1517814766_0579.png

- https://prod-cdn.sumo.mozilla.net/uploads/badge/2/6/26ed413cd3ad825d18590f987cc2d13a_image_1517820860_0173.png

**Comment by glogiotatidis** [comment]
It seems that django-badger is using ["Lots of hackery"](https://github.com/mozilla/django-badger/blob/master/badger/models.py#L88) when it comes to storing media files. 

Since the project is practically abandoned since 2016 we need to
 1. evaluate whether the whole badge awarding procedure is something we want to keep (SUMO team owns that). Take into consideration also that django-badger is related to the also abandoned badges.m.o project.
 2. If so evaluate whether we adopt or replace django-badger. There're [alternatives](https://djangopackages.org/grids/g/awards-badges/) listed in djangopackages.org
 3. Proceed with the plan

Will also comment in bugzilla to make the SUMO team aware of the situation.

**Comment by glogiotatidis** [comment]
Also since badger just writes to the FS, i've manually rsynced the badges from SCL3 to S3 and the images are working.

**Comment by glogiotatidis** [comment]
See also 
[SUMO Badges / Recognition Strategy after move of Kitsune to AWS](https://bugzilla.mozilla.org/show_bug.cgi?id=1439419)

**Comment by pmac** [comment]
django-badger also does not support Django 1.11 (or really any Django > 1.8). We'll need to deal with this as a perquisite for #3177.

**Comment by pmac** [comment]
That is a known issue with our current setup as well. It's because the model fields are not using our default storage systems, but trying to use file system specifically, which doesn't play well with how we do things in Docker and AWS. We do need to fix it, but I think we should do so after we land this first PR.

**Comment by pmac** [comment]
This is the issue pointed out in the original issue above and in the linked bugs.

**Comment by pmac** [comment]
The primary thing to test for the current changes is whether there are no changes from production functionality. We want to get rid of django-badger with no loss of function (people still have the badges they had, and people still get the badges they earn), and then we can improve things after that.
