### ISSUE TITLE
Support both OIDC and DB logins

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3151]
And restrict use of `/admin/` to users authenticated with OIDC only. I'll be investigating whether this is possible in this issue. If we can't support this quickly in a single instance we will deploy an admin-only version of kitsune that will only work with OIDC auth and allow use of the Admin, and turn off `/admin/` on SUMO proper.

/cc @glogiotatidis

**Comment by pmac** [comment]
I'm thinking we should be able to do this by detecting whether an authenticated user has certain OIDC keys in their session, e.g. ["oidc_id_token_expiration"](https://github.com/mozilla/mozilla-django-oidc/blob/5916a69ed7870053c4d4e194b45b42c2fac49496/mozilla_django_oidc/views.py#L54). Then we could have a separate middleware (or, more likely, a subclass of the OIDCRefresh middleware) that will only refresh the token on `/admin/*` URLs and will require a user to have those values in the session.

**Comment by jgmize** [comment]
Since https://github.com/mozilla/kitsune/commit/164afa6181c8854443bec56a33c858c30e2273fd has been pushed to production I have been unable to log in to the admin via OIDC/SSO. After authenticating, in the dev tools network panel I see 
- a 302 to `https://auth.mozilla.auth0.com/authorize?client_id=REDACTED&protocol=oauth2&redirect_uri=https://support.mozilla.org/oidc/callback/&nonce=REDACTED&response_type=code&scope=openid email&state=REDACTED&sso=true&connection=Mozilla-LDAP&tried_autologin=true`
- followed by a 302 to `https://auth.mozilla.auth0.com/login/callback?state=REDACTED` 
- then a 302 to `https://support.mozilla.org/oidc/callback/?code=REDACTED&state=REDACTED`
- and then a 302 to `/`
- and then I load the home page as an unauthenticated user
  - even if I had previously logged in using a username and password on https://support.mozilla.org/en-US/users/auth

This happens in both nightly and in chrome release channel
I know that multiple other users have been able to log in to the admin since we shipped this to production so I may be an edge case.

**Comment by glogiotatidis** [comment]
@jgmize  you need to use your ldap email address in sumo and not aliases. I changed it for you. it should be fine now. Please confirm.

**Comment by jgmize** [comment]
Thanks @glogiotatidis, that worked. I should have thought to check that.
