### ISSUE TITLE
Move from django-pipeline to Gulp for static asset processing

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3203]
Very much like I've done for bedrock in https://github.com/mozilla/bedrock/pull/5618 this covers removing django-pipeline and using a fully independent node:8 docker container for processing the static files as well as improving the developer experience. This may include significant changes to the docker strategy.

**Comment by gauravghati** [comment]
Hey @pmac and @madasan , I want to contribute to this repo, if no one is working on this issue, can I start working on it? I'm familiar with both Django and Gulp.

**Comment by LeoMcA** [comment]
Hey @gauravghati, this issue is quite outdated, we have some more thinking to do about our asset pipeline - I'll open a new issue about that before the end of the week giving our current thinking and requirements, and you're more than welcome to give feedback or experimentation on that.

For now, if you're looking for something to get stuck into we have a list of issues here: https://github.com/mozilla/sumo-project/issues?q=is%3Aopen+is%3Aissue+label%3Apr-welcome

**Comment by gauravghati** [comment]
@LeoMcA Sure, I'll checkout other issues. Thanks..
