### ISSUE TITLE
Allow filtering the questions API by date range

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3332]
The `created` and `updated` datetime fields should be filterable by ranges or other date-appropriate Django filter types (e.g. `month`, `hour`, `year`, etc.).

**Comment by LucianaMarques** [comment]
Hi there,

Is anyone working on this? I'd like to give this a try!

Thank you!

**Comment by turtlelovesshoes** [comment]
@LucianaMarques please feel free to make a pull request on this issue, feel free to ask any questions here or on #sumo-dev IRC channel.

**Comment by pmac** [comment]
IRC channel is `#sumodev` on the `irc.mozilla.org` network. See [the wiki](https://wiki.mozilla.org/IRC) for details.

**Comment by LucianaMarques** [comment]
Thank you! Will do!

**Comment by vaishnavipamulapati** [comment]
@LucianaMarques I've started work on this after discussion on the `#sumo` channel last week.

**Comment by LucianaMarques** [comment]
@vaishnavipamulapati I'm an Outreachy applicant and I just heard about this program (like some days ago) and found this issue. I have to submit a pull request until tomorrow to be eligible to apply for this project. 

Do you mind to work together on this? I have to submit a PR today and I don't know if I'll find another issue on time. Since I wasn't aware of this project a couple of days ago, I wasn't on the IRC channel so I didn't know that someone was already working on this, sorry :(

**Comment by vaishnavipamulapati** [comment]
@LucianaMarques Sure, I'll push my changes shortly so we can discuss what to do further.

**Comment by LucianaMarques** [comment]
@vaishnavipamulapati thank you so much! Let me know here when you push them and I'll take a look! I'm in #sumo now as lucianamarques, we can chat over there if you want

**Comment by rtanglao** [comment]
i would love to test this if somebody would let me know where the staging environment is!

**Comment by rtanglao** [comment]
@pmac @akatsoulas i think this was fixed! at least https://github.com/mozilla-it/sumo/blob/master/Kitsune/get_kitsune_data.py#L96 shows ```updated_lt``` and ```updated_gt``` for the questions API. if it is fixed, please close this issue

**Comment by akatsoulas** [comment]
Thanks @rtanglao for flagging this. Indeed it was fixed in this PR
https://github.com/mozilla/kitsune/pull/3483
