### ISSUE TITLE
Get Community Support -> Firefox OS Link Results in "This page is does not redirect properly error"

### ISSUE THREAD

**Issue by bensternthal** [mozilla/kitsune#3383]
From here:
https://support.mozilla.org/en-US/questions/new

Click:
https://support.mozilla.org/en-US/questions/new/firefox-os

Results in "The page isn’t redirecting properly" error.

**Comment by pmac** [comment]
Woah. After getting that error go back to the home page. I see:

![screenshot_2018-10-23 mozilla support](https://user-images.githubusercontent.com/19176817/47377765-25bede80-d6c4-11e8-859b-1c91f79528ef.png)

**Comment by pmac** [comment]
My guess right now is that someone removed the Firefox OS Product from the DB but it's still in AAQ b/c that requires a code change. I'll ask around.

**Comment by pmac** [comment]
The issue was that Firefox OS was removed from "English" in the "AAQ enabled locales" model. I added it back and all seems well. It seems this was done because there is a desire to remove FxOS from SUMO, but that will require a code change to be done properly. I expect a bug or issue for that soon. Thanks for reporting Ben!
