### ISSUE TITLE
[fxa] Header is broken on product page for all locales in Safari

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3625]
Env: 
macOS 10.13, Safari 12

**STR:**
Navigate to sumo homepage in dev
Click "Firefox" from Help articles section

**Expected:**
Header looks the same as on homepage

**Actual:**
Header is different from homepage, language selector and "Log In / Sign Up" buttons overlap "Download Firefox" button. This happens for all locales.

<img width="1274" alt="Screen Shot 2019-05-10 at 13 45 29" src="https://user-images.githubusercontent.com/5293100/57522244-dae87980-732a-11e9-96e7-11f6d9e92cb9.png">

**Comment by akatsoulas** [comment]
@kkellydesign can you take a look at this?

**Comment by kkellydesign** [comment]
This is fixed in the upcoming PR: 
https://github.com/lincolnloop/kitsune/commit/62db19f4c03d07fe27d08cd700539f0ff77e165e

Note that on this page, there's a conditional that removes the 'download firefox' button from the header, as the bigger button is supposed to appear lower on the page. (some recent changes had broken that out of the flow of where it should've been in the layout.) 

So here's the Firefox page in Safari: 
<img width="1453" alt="Screen Shot 2019-05-15 at 10 58 43 AM" src="https://user-images.githubusercontent.com/202590/57786220-1a371180-7701-11e9-827a-3cdb7691dd99.png">

And here's how the download button looks like on all of the pages except this one: 

<img width="1449" alt="Screen Shot 2019-05-15 at 11 06 01 AM" src="https://user-images.githubusercontent.com/202590/57786426-7306aa00-7701-11e9-8ac1-c723631f9563.png">

**Comment by mcranston18** [comment]
Will be fixed once https://github.com/mozilla/kitsune/pull/3636 is merged in
