### ISSUE TITLE
[FxA]: The header is not displayed when search bar is selected

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3680]
[Environment]:
iOS - Firefox, Safari

[STR]:
1.Open https://dev.sumo.moz.works/en-US/
2.Tap the search bar and start typing

[Expected result]:
The header should still be visible like on desktop

[Actual result]:
The search bar is in focus and the header is not displayed when the keyboard is displayed

![Image-1](https://user-images.githubusercontent.com/41474886/58264578-c377aa80-7d86-11e9-8ccc-94c5bebc8fe9.jpg)

**Comment by kkellydesign** [comment]
@viorelaioia @rleitan I see the issue here, but I'm not sure if it's a good idea to change this behavior. We have two different things going on: 

1) When the page is scrolled past the top, the header is tucked out of the way on both mobile and desktop. On most pages, the secondary header – just the logo and search bar – appears at that point. When a search result is open, however, this search bar is hidden. 

2) On iOS, when an input field is focused, the page is scrolled to that input. 

So the combination of these two things makes the header disappear when the search is focused. If you scroll the page back to the top, you'll see the header reappear, as expected. The solution to this would be to disable the header functionality that makes the primary header hide itself when the page scrolls. Personally, I think that's a nice feature to have, so I don't think we should make an exception for just this page. Let me know what you think.
