### ISSUE TITLE
[FxA] Avatar is broken when removing photo from firefox accounts

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3684]
**Preconditions:**
Have a sumo fxa account with an avatar added through Firefox Accounts management page

**STR:**
1. Login to your sumo account through fxa => The avatar is correctly displayed
2. Login to your firefox accounts management page in a new tab
3. Remove the avatar from your profile
4. Switch to the sumo tab (from step 1)
5. Navigate to a new page (e.g "My profile")

**Expected:**
Avatar is still displayed

**Actual:**
Avatar is broken 

**Note:**
If I logout then login again in sumo, the default avatar is displayed

![image](https://user-images.githubusercontent.com/5293100/58332106-38101f00-7e43-11e9-9f7e-28c3e09ae8eb.png)

**Comment by kkellydesign** [comment]
@akatsoulas I just added an avatar-fallback.png image to the static folder here, in case you want this feature to match the designs. If the blue/purple image is intended, I've also removed the grey background from `.avatar-preview` so that looks a little better. It appears that all of the fallback image swapping happens on the backend though, so I've done all I can on the frontend here. 

FYI – I also removed a frontend fallback that was never actually working. I had written a conditional in django that never actually returned false, so my fallback was never used. 

https://github.com/mozilla/kitsune/commit/9960cec52f29cd80225a8f26145d9a17b3b2c22d
