### ISSUE TITLE
[FxA] confirmation email text from FxA is "sumo_dev_cluster"

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3688]
Current experience: 

New account creation, after email verification, confirmation message says:
"You are now ready to use sumo_dev_cluster"

Expected Experience:
"You are now ready to use support.mozilla.org"

**Comment by akatsoulas** [comment]
Thanks @flekkowich for filing this. The confirmation message comes from the configuration of the client in Firefox Accounts and it's configured like this only for dev in order to help us distinguish between the multiple clients that we are using for the development process. In the prod instance the sumo_dev_cluster will be replaced by `Mozilla Support` but we can update it if needed.

**Comment by flekkowich** [comment]
@akatsoulas this seems to still be a problem upon login  - can we get this changed prior to Tuesday?
