### ISSUE TITLE
[FxA] Design issues - profile page

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3697]
1. Dropdown arrow is too big. Arrow size is 5 x 10 px
2. Items missing - see designs https://projects.invisionapp.com/d/main#/console/17173078/359491675/preview
3. Button: Button size should be 120 x 40 px.Font size should be 16 pt.All black buttons have a hover and a “click” state:static: HEX #000000hover: HEX #1C1C1Cclick: HEX #0B0B0B

[See page 7](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

**Comment by kkellydesign** [comment]
Items 1 and 3 are in https://github.com/mozilla/kitsune/pull/3711.

<img width="969" alt="Screen Shot 2019-06-03 at 4 27 23 PM" src="https://user-images.githubusercontent.com/202590/58832242-87f99d80-861c-11e9-8030-e8c4b48688c1.png">

For item #2, I'll need some help from @mcranston18 or @nicolaslara. Here's a screenshot of the request in question. Notice from the content that they are testing from a FF-account user: 

<img width="820" alt="Screen Shot 2019-06-03 at 4 24 32 PM" src="https://user-images.githubusercontent.com/202590/58832278-9c3d9a80-861c-11e9-9385-2c8cbb9c2e91.png">

But I'm working locally on a SUMO account, which has the required info: 
<img width="967" alt="Screen Shot 2019-06-03 at 4 28 28 PM" src="https://user-images.githubusercontent.com/202590/58832329-b6777880-861c-11e9-8322-44e05a253c73.png">

So we have two options: 1) Since the design is all there for sumo accounts, please change conditionals or port that info over to the correct template. Or 2), let me know how to test a Firefox account. If I try to set one up locally I get "Bad Request: Incorrect redirect_uri." This is the only ticket so far where this has caused a problem for me, but there may be more.

**Comment by kkellydesign** [comment]
update from this morning's call: 
- [ ] Username, etc. are displayed conditionally, so the testing data was likely incomplete. Verify locally that conditionals work
- [ ] align items to the top so when there are only one or two, they don't center-justify with the photo

**Comment by kkellydesign** [comment]
confirmed – the conditionals work correctly. I just aligned the items to the top instead of the center. I think we're set with this: 
<img width="710" alt="Screen Shot 2019-06-04 at 1 54 01 PM" src="https://user-images.githubusercontent.com/202590/58901973-3f032100-86d0-11e9-9845-c82dac9c38d3.png">
