### ISSUE TITLE
The search bar is not cleared when pressing Delete tab

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3731]
[Environment]:
Windows 10- Chrome

[STR]:
1.Open https://support-dev.allizom.org/en-US/
2.Type something in the search bar
3.Select all entered text and press Delete button

[Expected result]:
All text should be deleted, the search bar should display "Find help.." text

[Actual result]:
The first letters are still displayed
https://drive.google.com/file/d/1ELMyHkLYxTF8Ye9cvONm18QqzTGzZEDP/view

[Note]:
The issue is not reproducible on Firefox

@kkellydesign

**Comment by kkellydesign** [comment]
I'm not able to reproduce this issue on production, but I am seeing on both the link you provided and http://dev.sumo.moz.works/, intermittently. It's only happening on Chrome for Windows – not on mac – and Firefox and Edge are working fine. 

The search feature is built with javascript that contains both react and jquery, and I made a point to leave the HTML alone for this piece so that the javascript here wouldn't be affected by my style edits. My guess as to why this is happening on the dev sites and not on production is that since the search is pinging the index from the backend on every keypress, the slower dev servers might be having a harder time keeping up. 

I think it's a good idea to revisit the search in the next round of work on this project, but for this particular ticket, I think this might go away once this code is shipped to the production server. 

@nicolaslara and @akatsoulas might have other thoughts on this, but I'm fairly certain that this isn't an issue with the HTML/CSS work that I did for this project.
