### ISSUE TITLE
[fxa]: Broken layout on https://support-dev.allizom.org/en-US/products/ios page

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3760]
[Environment]:
Windows 10 - Firefox, Chrome

[STR]:
1. Open https://support-dev.allizom.org/en-US/products/ios

[Actual result]:

![2019-06-26_17h44_36](https://user-images.githubusercontent.com/41474886/60190048-a8db9a00-983a-11e9-9a13-7574bc8e50ea.png)

@kkellydesign

**Comment by kkellydesign** [comment]
That's the alt tag of a missing image. On production, that will be an image file. On my local instance, there's a working fallback image, so I'm not sure why that doesn't exist on your dev server. Regardless, it's a fairly straightforward fix to add a `font-size` to the image tag in CSS to fix this, so it's done. This is a weird edge-case on your testing server though, which I was able to reproduce by breaking the source of the image in devtools. This is fixed in https://github.com/mozilla/kitsune/pull/3764

<img width="927" alt="Screen Shot 2019-06-26 at 1 07 13 PM" src="https://user-images.githubusercontent.com/202590/60200456-27711100-9814-11e9-8a15-8588900e6a1b.png">
