### ISSUE TITLE
[fxa] front page items do not organise into grid of 3 when minimized

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3775]
Current behavior
menu items take full space of minimized page https://support-dev.allizom.org/en-US/

Expected behavior
Grid of menu items. https://support.mozilla.org/en-US/

**Comment by kkellydesign** [comment]
@flekkowich I'm not sure what you mean by 'minimized' here. We only have one breakpoint on this system, and it's where the navigation breaks from mobile to desktop. On the mobile size, I'm stacking these items because displaying them at 33% doesn't work on mobile. 

When we rework the frontend I can build this to be a bit more flexible, displaying items at 100% wide on mobile, 50% on tablet sizes, and 33% on desktop. But since there were no designs provided for those breakpoints, I opted to keep it simple for this interim step.

**Comment by rleitan** [comment]
Just to confirm, on tablet view, the grid has 2 products displayed 

![2019-07-02_16h32_41](https://user-images.githubusercontent.com/41474886/60516733-04000780-9ce7-11e9-9668-5f70110fdd6c.png)

@flekkowich

**Comment by kkellydesign** [comment]
@rleitan asked that I re-confirm with @flekkowich: I added a fix yesterday to go from 1 column on mobile, to two on tablet, to three on desktop. Please let me know if you had something different in mind.

https://support.allizom.org/en-US/

**Comment by flekkowich** [comment]
@kkellydesign confirmed sounds like a good solution.
