### ISSUE TITLE
[fxa] top menu items not aligned 

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3792]
Top menu EN / username not bottom aligned - ensure in fix also aligned w/ rest of the menu. 

<img width="195" alt="Screen Shot 2019-07-02 at 10 32 13 AM" src="https://user-images.githubusercontent.com/4169599/60533568-c4202c80-9cb4-11e9-8ff8-fc207109a1f5.png">

cc @kkellydesign

**Comment by kkellydesign** [comment]
Hi @flekkowich – 

If you zoom in and measure that, the bottom of the "N" and the bottom of the "r" do line up correctly. It just looks a little off because your username isn't capitalized. I could nudge it around so it looks more correct visually, but then it'd look crooked when the username starts with a taller letter. I think we ought to leave this one alone. 

<img width="637" alt="Screen Shot 2019-07-10 at 5 13 50 PM" src="https://user-images.githubusercontent.com/202590/61005414-2375e080-a336-11e9-987e-9701e817f825.png">

**Comment by flekkowich** [comment]
hi Kelly

Ok makes sense! Sorry to bother, I should have checked myself!

**Comment by akatsoulas** [comment]
Closing per last comment.
