### ISSUE TITLE
 Reply box text area size and font too small

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3812]
See bug 
https://bugzilla.mozilla.org/show_bug.cgi?id=1563348

**Comment by kkellydesign** [comment]
This fix is in. I didn't make this global on all textareas because that would deviate from the provided designs, but I did fix the field in question. You can see an example when you're logged in here: 

https://support.allizom.org/en-US/kb/containers/discuss/7459

<img width="826" alt="Screen Shot 2019-07-12 at 10 09 41 AM" src="https://user-images.githubusercontent.com/202590/61134392-80d07580-a48d-11e9-8113-3179cb129b9a.png">

**Comment by rleitan** [comment]
I confirm it's fixed in the text boxes for reply displayed on discussions pages.

**Comment by akatsoulas** [comment]
This is live in prod

**Comment by AliceWyman** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1563348 has been reopened. The reply box is now larger in the contributor discussion forums and in the KB article discussions but the size of the reply box in the support (Questions) forum is still small.  For example, see the Post a Reply box at the end of this thread: https://support.mozilla.org/en-US/questions/1265238

**Comment by kkellydesign** [comment]
This is fixed: https://github.com/lincolnloop/kitsune/commit/850776fac9f19aae5eb6d85823ef689caba7b3aa

<img width="755" alt="Screen Shot 2019-07-24 at 10 42 41 AM" src="https://user-images.githubusercontent.com/202590/61803239-cda63b80-adff-11e9-94df-cdb3fdf781d2.png">
