### ISSUE TITLE
{for}markup is not recognized on in Lockwise articles

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3876]
Lockwise articles are not recognizing {for}{/for} content despite version 70 being visible in https://support.mozilla.org/admin/products/version/ 

**STR:**
Add {for not fx70}{/for} around any content in any Lockwise article (example: https://support.mozilla.org/en-US/kb/manage-passwords-firefox-desktop-firefox-lockwise)

**Expected result:**
The content should not show up in Nightly and the version picker should show up.

**Actual result**
The version picker does not show up. The marked up content is still visible.

**Comment by akatsoulas** [comment]
This issue was discussed in a meeting and it was decided that it won't be fixed. {for} markup is designed to work when the product has a user agent (eg Firefox) and it matches the version of the product stored in the DB with the one of the user agent. Lockwise does not have a user agent thus the markup is not recognized. As a workaround different versions of an article will be provided to the end user.
