### ISSUE TITLE
Error page returned when editing image description

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3918]
**STR:**
1. Login to Sumo staging
2. Navigate to Gallery page (/gallery/images)
3. Click "Upload a new file" button
4. Add a photo that was not uploaded in sumo staging before
5. Navigate to Gallery page 
6. Click the photo that was uploaded in step 4
7. Click "Edit this photo"
8. Update the description and click "Save Image"

**Expected:**
Image description is successfully saved, image page is returned

**Actual:**
Error page is returned. See [video](https://drive.google.com/file/d/1FLIH-yhvXFnqccqOPLixYoSIJ0cYFkN-/view?usp=sharing)
This is not happening in prod, by following same steps 

![image](https://user-images.githubusercontent.com/5293100/66392970-0060d880-e9da-11e9-873e-27ed11cccb68.png)

**Comment by butowskii** [comment]
I would like to solve this issue.

**Comment by akatsoulas** [comment]
HI @butowskii! You can start working on this issue by following these [instructions](https://github.com/mozilla/kitsune#development) to setup the project in your local machine. Please let me know if you need any additional help.

**Comment by butowskii** [comment]
I dont satisfy pre-requisites of docker on my system(don't have the required OS).Can I still work on without Docker.
thanks

**Comment by akatsoulas** [comment]
You should be able to install and use docker in your OS too. Which OS are you using?

**Comment by butowskii** [comment]
windows 10 home

**Comment by saadmk11** [comment]
The server is throws `500` error because of this:

https://github.com/mozilla/kitsune/blob/12cb18dca71a01b0b4f50cfbe2e159b2f2d1e367/kitsune/gallery/models.py#L26

If a user edits the description of an image then `is_draft` is set to `False`.
Next time when the user tries to edit another image and django tries to set `is_draft=False` for the second image.
So, the `unique_together` constraint fails as there is already an image with the same `creator` and `is_draft=False`.

I'm not quite sure why we use `unique_together` for `('is_draft', 'creator')` as I'm new to this repository.

**Comment by zzpzzh** [comment]
BSD 2-Clause License

Copyright (c) [year], [fullname]
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by zzpzzh** [comment]
BSD 2-Clause License

Copyright (c) [year], [fullname]
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by zzpzzh** [comment]
Ok

**Comment by LeoMcA** [comment]
@saadmk11 thanks for debugging this, I just came across this issue having come to the same conclusion from another bug report a few days ago: https://github.com/mozilla/sumo-project/issues/547
