### ISSUE TITLE
Is there a memory leak in Firefox?

### ISSUE THREAD

**Issue by SunYu2004** [mozilla/kitsune#5595]
Using Firefox China Edition.Is there a memory leak problem? After opening firefox, the memory usage is going to higher and higher, even to 4GiB or even more.

**Comment by SunYu2004** [comment]
This problem only occurs these days, and haven't been found before.

**Comment by emilghittasv** [comment]
Hey @SunYu2004,

I don't think that your issue is filled in the correct place. This is the repo which powers [SuMo (support.mozilla.org)](https://support.mozilla.org/)

For issues related to one of our products please file a ticket in https://bugzilla.mozilla.org/home or feel free to ask a question/get support via the https://support.mozilla.org/en-US/ page.
